title: homey
minimal_mode: false
hide_house: false
compact_services: false
enable_service_status: true
enable_notifications: true
audio_notifications: true
docker_api_backend: docker
services:
- icon: portainer.png
  name: Portainer
  subtitle: Docker container management
  url: https://192.168.1.5:9443
- icon: flood.png
  name: Flood
  subtitle: Web UI for rTorrent
  url: http://192.168.1.5:9005
- icon: navidrome.png
  name: Navidrome
  subtitle: Music streaming
  url: http://192.168.1.5:9004
- icon: jellyfin.png
  name: Jellyfin
  subtitle: Video streaming
  url: http://192.168.1.5:9002
- icon: sonarr.png
  name: Sonarr
  subtitle: Automated TV downloads
  url: http://192.168.1.5:9012
- icon: jackett.png
  name: Jackett
  subtitle: Sonarr indexing service
  url: http://192.168.1.5:9004/app/#/login
- icon: mealie.png
  name: Mealie
  subtitle: Recipe collection
  url: http://192.168.1.5:9004/app/#/login
- icon: hoppscotch.png
  name: Hoppscotch
  subtitle: Rapid API development
  url: http://192.168.1.5:9007
- icon: nextcloud.png
  name: Nextcloud
  subtitle: Online file storage
  url: http://redacted
- icon: nginx-proxy-manager.png
  name: NGINX Proxy Manager
  subtitle: Reverse proxy manager
  url: http://192.168.1.5:81
cards:
- enable: true
  name: Torrents
- enable: true
  name: Weather
- enable: true
  name: System
- enable: true
  name: Bookmarks
bookmarks:
- name: GitHub
  url: https://github.com
  hover: null
- name: YTMND
  url: https://ytmnd.com/
  hover: lol internet
