version: "3.1"

# Please refer to readme before running docker-compose up

services:
  homey-api:
    container_name: homey-api
    hostname: homey-api
    image: vlfldr/homey-api:latest
    build: ./homey-api/
    user: "${HOMEY_API_DOCKER_USER_ID}:${HOMEY_API_DOCKER_GROUP_ID}"
    env_file: .env
    ports: 
      - "9101:9101"
    volumes:
      - /var/run/docker.sock:${HOMEY_API_DOCKER_SOCKET}
      - ~/homey-data:/code/config

  homey:
    container_name: homey
    hostname: homey
    image: vlfldr/homey:latest
    build: ./homey/
    ports:
      - "9080:80"
    volumes:
      - ~/homey-data:/app/data
    depends_on:
      - "homey-api"
