version: "3.1"

services:
  homey-api:
    container_name: homey-api
    hostname: homey-api
    image: vlfldr/homey-api:latest
    build: ./homey-api/
    user: "${HOMEY_API_DOCKER_USER_ID}:${HOMEY_API_DOCKER_GROUP_ID}"
    env_file: .env
    ports: 
      - "9101:9101"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  homey:
    container_name: homey
    hostname: homey
    image: vlfldr/homey:latest
    build: ./homey/
    ports:
      - "8080:8080"
    depends_on:
      - "homey-api"
