version: "3.1"

services:
  homey-api:
    build: .
    user: "${HOMEY_API_DOCKER_USER_ID}:${HOMEY_API_DOCKER_GROUP_ID}"
    ports: 
      - "9101:9101"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock