compact_services: false
docker_api_backend: portainer
enable_service_status: true
minimal_mode: false
services:
- icon: portainer.png
  name: Portainer
  subtitle: Docker container management
  url: https://192.168.1.5:9443
- icon: flood.png
  name: Flood
  subtitle: Web UI for rTorrent
  url: http://192.168.1.5:9005
- icon: navidrome.png
  name: Navidrome
  subtitle: Music streaming
  url: http://192.168.1.5:9004/app/#/login
- icon: flood.png
  name: aS
  subtitle: a
  url: a
title: homey
