# valid options: docker, portainer
docker_api_backend: "portainer"

# toggle up/down indicators on service cards
enable_service_status: true

# additional service icons: https://github.com/vlfldr/homer-icons
services:
  - name: "Portainer"
    icon: "portainer.png"
    subtitle: "Docker container management"
    url: "https://192.168.1.5:9443"
  - name: "Flood"
    icon: "flood.png"
    subtitle: "Web UI for rTorrent"
    url: "http://192.168.1.5:9005"
  - name: "Navidrome"
    icon: "navidrome.png"
    subtitle: "Music streaming"
    url: "http://music.mntn.top"

