services:
  - name: "Flood"
    icon: "flood.png"
    subtitle: "Web UI for rtorrent"
    url: "http://192.168.1.5:9005"
  
  - name: "Navidrome"
    icon: "navidrome.png"
    subtitle: "Music streaming"
    url: "https://music.mntn.top"

  - name: "Jellyfin"
    icon: "jellyfin.png"
    subtitle: "Video streaming"
    url: "https://tv.mntn.top"
  
  - name: "Vaultwarden"
    icon: "vaultwarden.png"
    subtitle: "Password manager"
    url: "https://vault.mntn.top"

  - name: "NGINX Proxy Manager"
    icon: "nginx-proxy-manager.png"
    subtitle: "Reverse proxy management"
    url: "http://localhost:81"

  - name: "Portainer"
    icon: "portainer.png"
    subtitle: "Web UI for Docker"
    url: "https://localhost:9443"
  
  - name: "Whoogle"
    icon: "whoogle.png"
    subtitle: "Anonymous search engine"
    url: "https://mntn.top"

  - name: "Jackett"
    icon: "jackett.png"
    subtitle: "Private tracker metasearch"
    url: "http://localhost:9006"

  - name: "Mealie"
    icon: "mealie.png"
    subtitle: "Recipe collection & organizer"
    url: "http://localhost:9008"

  - name: "Hoppscotch"
    icon: "hoppscotch.png"
    subtitle: "Rapid API development"
    url: "http://localhost:9007"