# config.yaml
---
services:
  - name: "Flood"
    icon: "flood.png"
    subtitle: "Web UI for rtorrent"
    url: "http://192.168.1.5:9005"
  
  - name: "Navidrome"
    icon: "navidrome.png"
    subtitle: "Music streaming"
    url: "https://music.mntn.top"

  - name: "Jellyfin"
    icon: "jellyfin.png"
    subtitle: "Video streaming"
    url: "https://tv.mntn.top"
  
  - name: "Vaultwarden"
    icon: "bitwarden.png"
    subtitle: "Password manager"
    url: "https://vault.mntn.top"