// Layout & fill order for Docker whale grid

// We could do it in one line with x = (index % 5) y = floor(index / 5),
// but that's boring and doesn't take long enough...

export default { 
    CrateIndexes: [  
    { y: 0, x: 4 },
    { y: 0, x: 3 },
    { y: 1, x: 4 },
    { y: 0, x: 2 },
    { y: 1, x: 3 },
    { y: 0, x: 5 },
    { y: 0, x: 1 },
    { y: 2, x: 4 },
    { y: 1, x: 2 },
    { y: 3, x: 4 },
    { y: 2, x: 2 },
    { y: 1, x: 5 },
    { y: 2, x: 3 },
    { y: 1, x: 1 },
    { y: 2, x: 1 },
    { y: 3, x: 3 },
    { y: 4, x: 4 },
    { y: 2, x: 5 },
    { y: 3, x: 1 },
    { y: 3, x: 5 },
    { y: 4, x: 1 },
    { y: 5, x: 4 },
    { y: 4, x: 3 },
    { y: 3, x: 2 },
    { y: 4, x: 5 },
    { y: 5, x: 1 },
    { y: 4, x: 2 },
    { y: 5, x: 5 },
    { y: 5, x: 2 },
    { y: 6, x: 2 },
    { y: 6, x: 4 },
    { y: 7, x: 4 },
    { y: 6, x: 1 },
    { y: 7, x: 1 },
    { y: 6, x: 5 },
    { y: 5, x: 3 },
    { y: 7, x: 5 },
    { y: 6, x: 3 },
    { y: 7, x: 2 },
    { y: 7, x: 3 }
] }
